# Generated by Django 5.0.1 on 2024-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
                ('country_lat', models.FloatField(null=True)),
                ('country_lon', models.FloatField(null=True)),
                ('code_100cols', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
