# Generated by Django 3.2.24 on 2024-02-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_info',
            fields=[
                ('act_info_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('act_id', models.IntegerField(null=True)),
                ('info_txt', models.CharField(default='--', max_length=100)),
            ],
        ),
    ]
