# Generated by Django 5.0.1 on 2024-01-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('strava_id', models.IntegerField(default=0)),
                ('strava_user_id', models.IntegerField()),
                ('act_name', models.CharField(default='', max_length=200, null=True)),
                ('act_start_date', models.DateTimeField()),
                ('act_dist', models.FloatField(null=True)),
                ('act_den', models.IntegerField(null=True)),
                ('act_type', models.CharField(max_length=10, null=True)),
                ('act_time', models.IntegerField(null=True)),
                ('act_power', models.IntegerField(null=True)),
                ('act_status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Col',
            fields=[
                ('col_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('col_name', models.CharField(max_length=200)),
                ('col_code', models.CharField(max_length=20, null=True, unique=True)),
                ('col_alt', models.IntegerField(null=True)),
                ('col_lat', models.FloatField(null=True)),
                ('col_lon', models.FloatField(null=True)),
                ('col_type', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Col_counter',
            fields=[
                ('col_count_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('col_code', models.CharField(default='-', max_length=20)),
                ('strava_user_id', models.IntegerField()),
                ('col_count', models.IntegerField()),
                ('year_col_count', models.IntegerField(default=0)),
                ('last_passage_date', models.DateTimeField(null=True)),
                ('last_act_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Col_perform',
            fields=[
                ('col_perf_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('col_code', models.CharField(default='-', max_length=20)),
                ('strava_id', models.IntegerField()),
            ],
            options={
                'ordering': ['-strava_id'],
            },
        ),
        migrations.CreateModel(
            name='Month_stat',
            fields=[
                ('month_stat_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('strava_user_id', models.IntegerField(null=True)),
                ('yearmonth', models.CharField(default='190000', max_length=6)),
                ('days_on', models.IntegerField(null=True)),
                ('bike_km', models.IntegerField(null=True)),
                ('bike_ascent', models.IntegerField(null=True)),
                ('bike_time', models.IntegerField(null=True)),
                ('col_count', models.IntegerField(null=True)),
                ('col2000_count', models.IntegerField(null=True)),
                ('top_alt_col', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('perform_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('strava_perf_id', models.IntegerField(null=True)),
                ('segment_id', models.IntegerField()),
                ('strava_user_id', models.IntegerField(null=True)),
                ('perf_date', models.DateTimeField()),
                ('perf_chrono', models.IntegerField()),
                ('perf_vam', models.IntegerField()),
                ('perf_fc', models.IntegerField()),
                ('perf_fcmax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=50)),
                ('region_code', models.CharField(default='', max_length=50, null=True)),
                ('country_code', models.CharField(default='', max_length=3)),
                ('region_lat', models.FloatField(null=True)),
                ('region_lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('segment_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('strava_segment_id', models.IntegerField(null=True)),
                ('activity_type', models.CharField(default='-', max_length=20)),
                ('segment_name', models.CharField(default='-', max_length=100)),
                ('slope', models.FloatField(null=True)),
                ('lenght', models.FloatField(null=True)),
                ('ascent', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strava_user',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('strava_user_id', models.IntegerField(null=True)),
                ('strava_user', models.CharField(default='-', max_length=100)),
                ('first_name', models.CharField(default='-', max_length=100)),
                ('last_name', models.CharField(default='-', max_length=100)),
                ('token_type', models.CharField(default='-', max_length=100)),
                ('access_token', models.CharField(default='-', max_length=100)),
                ('refresh_token', models.CharField(default='-', max_length=100)),
                ('expire_at', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_dashboard',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('strava_user_id', models.IntegerField(null=True)),
                ('col_count', models.IntegerField(null=True)),
                ('col2000_count', models.IntegerField(null=True)),
                ('bike_year_km', models.IntegerField(null=True)),
                ('run_year_km', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_var',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('strava_user_id', models.IntegerField(null=True)),
                ('view_country_code', models.CharField(default='FRA', max_length=20)),
                ('view_region_code', models.CharField(default='06', max_length=20)),
                ('last_update', models.IntegerField(null=True)),
            ],
        ),
    ]
