# Generated by Django 3.2.24 on 2024-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_activity_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_info',
            name='act_id',
        ),
        migrations.AddField(
            model_name='activity_info',
            name='strava_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity_info',
            name='info_txt',
            field=models.TextField(),
        ),
    ]
